/**
 * presets.js
 * Full effect presets - v0.2.0
 * Completely reworked for maximum visual impact using trails, blend modes,
 * death sparks, gradients, and the full emitter/motion toolkit.
 */

const EFFECT_PRESETS = {
  fire: {
    label: 'Fire',
    palette: 'fire',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 26, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.92,
      count: 300, spawnRate: 180, speed: 3.2, spread: 24, direction: 268,
      gravity: -0.65, turbulence: 1.4, drag: 0.965, wind: 0.03, orbit: 0.22,
      particleSize: 4, particleShape: 'triangle', sizeVariance: 2, hueVariation: 15,
      blendMode: 'glow', effectStrength: 1.85, startAlpha: 1, twinkle: 0.15, rotation: 4,
      lifetime: 75, fade: 1, shrink: 0.42,
      speedVariance: 0.5, velocityDecay: 0.18,
      deathCount: 3, deathSpeed: 1.8, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#fff7c0',
      gradientEnd: '#4a0800',
      gradientStops: ['#fff7c0', '#ffb833', '#ff4400', '#4a0800'],
      bgColor: '#060306', trailAlpha: 0.12,
      trailEnabled: true, trailPersistence: 22, trailOpacity: 92, trailSoftness: 6,
    },
  },

  snow: {
    label: 'Snow',
    palette: 'ice',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 50, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.0,
      count: 200, spawnRate: 48, speed: 0.7, spread: 30, direction: 94,
      gravity: 0.08, turbulence: 1.1, drag: 0.994, wind: 0.18, orbit: 0,
      particleSize: 3, particleShape: 'sparkle', sizeVariance: 2, hueVariation: 5,
      blendMode: 'glow', effectStrength: 0.55, startAlpha: 0.85, twinkle: 0.35, rotation: 3,
      lifetime: 340, fade: 0.45, shrink: 0.02,
      speedVariance: 0.5, velocityDecay: 0.01,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#1e3d6b',
      gradientStops: ['#ffffff', '#c8e5ff', '#6ba4d9', '#1e3d6b'],
      bgColor: '#04081a', trailAlpha: 0.025,
      trailEnabled: true, trailPersistence: 5, trailOpacity: 60, trailSoftness: 22,
    },
  },

  explosion: {
    label: 'Explosion',
    palette: 'lava',
    cfg: {
      emitterShape: 'point', emitterMode: 'burst', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 400, spawnRate: 400, speed: 8.5, spread: 360, direction: 270,
      gravity: 0.3, turbulence: 0.4, drag: 0.91, wind: 0, orbit: 0,
      particleSize: 4, particleShape: 'square', sizeVariance: 2, hueVariation: 25,
      blendMode: 'glow', effectStrength: 2.0, startAlpha: 1, twinkle: 0.08, rotation: 6,
      lifetime: 55, fade: 1, shrink: 0.65,
      speedVariance: 0.6, velocityDecay: 0.38,
      deathCount: 6, deathSpeed: 3.5, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#fffde0',
      gradientEnd: '#2d0000',
      gradientStops: ['#fffde0', '#ffc040', '#ff3300', '#2d0000'],
      bgColor: '#050304', trailAlpha: 0.2,
      trailEnabled: true, trailPersistence: 32, trailOpacity: 95, trailSoftness: 3,
    },
  },

  sparkle: {
    label: 'Sparkle',
    palette: 'candy',
    cfg: {
      emitterShape: 'disk', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 22, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.48,
      count: 150, spawnRate: 60, speed: 1.2, spread: 360, direction: 270,
      gravity: -0.06, turbulence: 0.45, drag: 0.994, wind: 0, orbit: 0.4,
      particleSize: 5, particleShape: 'sparkle', sizeVariance: 3, hueVariation: 30,
      blendMode: 'prism', effectStrength: 1.3, startAlpha: 1, twinkle: 1.2, rotation: 12,
      lifetime: 105, fade: 1, shrink: 0.55,
      speedVariance: 0.35, velocityDecay: 0.05,
      deathCount: 1, deathSpeed: 1.5, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#fff8ff',
      gradientEnd: '#7a2dff',
      gradientStops: ['#fff8ff', '#ffaaee', '#cc66ff', '#7a2dff'],
      bgColor: '#05030e', trailAlpha: 0.04,
      trailEnabled: true, trailPersistence: 8, trailOpacity: 70, trailSoftness: 5,
    },
  },

  magic: {
    label: 'Magic',
    palette: 'magic',
    cfg: {
      emitterShape: 'arc', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 20, emitterAngle: 270, emitterArc: 120, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.7,
      count: 200, spawnRate: 85, speed: 3.2, spread: 50, direction: 266,
      gravity: -0.5, turbulence: 1.35, drag: 0.97, wind: 0, orbit: 0.8,
      particleSize: 4, particleShape: 'star', sizeVariance: 2, hueVariation: 35,
      blendMode: 'prism', effectStrength: 1.4, startAlpha: 1, twinkle: 0.8, rotation: 8,
      lifetime: 110, fade: 1, shrink: 0.48,
      speedVariance: 0.35, velocityDecay: 0.12,
      deathCount: 3, deathSpeed: 2.0, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffe0ff',
      gradientEnd: '#2a0866',
      gradientStops: ['#ffe0ff', '#d070ff', '#7030cc', '#2a0866'],
      bgColor: '#04020c', trailAlpha: 0.08,
      trailEnabled: true, trailPersistence: 18, trailOpacity: 88, trailSoftness: 10,
    },
  },

  smoke: {
    label: 'Smoke',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 12, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.92,
      count: 80, spawnRate: 20, speed: 0.5, spread: 18, direction: 268,
      gravity: -0.42, turbulence: 0.9, drag: 0.985, wind: 0.1, orbit: 0,
      particleSize: 10, particleShape: 'circle', sizeVariance: 5, hueVariation: 0,
      blendMode: 'shadow', effectStrength: 1.2, shadowColor: '#1a1520',
      startAlpha: 0.22, twinkle: 0, rotation: 0,
      lifetime: 300, fade: 0.85, shrink: -0.55,
      speedVariance: 0.2, velocityDecay: 0.25,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: false, useGradient: false,
      singleColor: '#a09aa8',
      gradientStart: '#a09aa8',
      gradientEnd: '#3a3440',
      bgColor: '#08080c', trailAlpha: 0.02,
      trailEnabled: true, trailPersistence: 6, trailOpacity: 50, trailSoftness: 40,
    },
  },

  confetti: {
    label: 'Confetti',
    palette: 'retro',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 50, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.0,
      count: 180, spawnRate: 80, speed: 5.0, spread: 50, direction: 92,
      gravity: 0.35, turbulence: 1.2, drag: 0.988, wind: 0.04, orbit: 0,
      particleSize: 5, particleShape: 'square', sizeVariance: 2, hueVariation: 35,
      blendMode: 'normal', effectStrength: 0.85, startAlpha: 1, twinkle: 0.1, rotation: 18,
      lifetime: 190, fade: 0.3, shrink: 0,
      speedVariance: 0.55, velocityDecay: 0.04,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: false,
      gradientStart: '#ffb400',
      gradientEnd: '#ff5e5b',
      bgColor: '#080810', trailAlpha: 0.05,
      trailEnabled: true, trailPersistence: 8, trailOpacity: 75, trailSoftness: 0,
    },
  },

  portal: {
    label: 'Portal',
    palette: 'aurora',
    cfg: {
      emitterShape: 'circle', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 300, spawnRate: 110, speed: 2.5, spread: 360, direction: 270,
      gravity: 0, turbulence: 0.1, drag: 0.984, wind: 0, orbit: 2.2,
      particleSize: 3, particleShape: 'ring', sizeVariance: 2, hueVariation: 22,
      blendMode: 'prism', effectStrength: 1.5, startAlpha: 0.95, twinkle: 0.6, rotation: 3,
      lifetime: 85, fade: 1, shrink: 0.7,
      speedVariance: 0.2, velocityDecay: 0.28,
      deathCount: 1, deathSpeed: 2.5, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#e0ffff',
      gradientEnd: '#0a0330',
      gradientStops: ['#e0ffff', '#50d0ff', '#9040ff', '#0a0330'],
      bgColor: '#020210', trailAlpha: 0.16,
      trailEnabled: true, trailPersistence: 26, trailOpacity: 92, trailSoftness: 8,
    },
  },

  rain: {
    label: 'Rain',
    palette: 'ocean',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 50, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.0,
      count: 380, spawnRate: 300, speed: 10, spread: 4, direction: 96,
      gravity: 0.05, turbulence: 0.02, drag: 1, wind: 0.1, orbit: 0,
      particleSize: 2, particleShape: 'square', sizeVariance: 0, hueVariation: 3,
      blendMode: 'shadow', effectStrength: 0.9, shadowColor: '#061530',
      startAlpha: 0.5, twinkle: 0, rotation: 0,
      lifetime: 52, fade: 0.7, shrink: 0,
      speedVariance: 0.2, velocityDecay: 0,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#c4e8ff',
      gradientEnd: '#0a3870',
      gradientStops: ['#c4e8ff', '#5599cc', '#0a3870'],
      bgColor: '#020610', trailAlpha: 0.22,
      trailEnabled: true, trailPersistence: 34, trailOpacity: 88, trailSoftness: 0,
    },
  },

  healing: {
    label: 'Healing',
    palette: 'nature',
    cfg: {
      emitterShape: 'circle', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 14, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 130, spawnRate: 40, speed: 0.8, spread: 360, direction: 270,
      gravity: -0.32, turbulence: 0.6, drag: 0.988, wind: 0, orbit: 0.5,
      particleSize: 5, particleShape: 'heart', sizeVariance: 2, hueVariation: 14,
      blendMode: 'glow', effectStrength: 1.4, startAlpha: 0.95, twinkle: 0.4, rotation: 4,
      lifetime: 155, fade: 1, shrink: 0.38,
      speedVariance: 0.28, velocityDecay: 0.08,
      deathCount: 2, deathSpeed: 1.2, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#f0ffe0',
      gradientEnd: '#0d7a30',
      gradientStops: ['#f0ffe0', '#80ff70', '#30cc50', '#0d7a30'],
      bgColor: '#020804', trailAlpha: 0.045,
      trailEnabled: true, trailPersistence: 10, trailOpacity: 72, trailSoftness: 18,
    },
  },

  electric: {
    label: 'Electric',
    palette: 'neon',
    cfg: {
      emitterShape: 'point', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 220, spawnRate: 200, speed: 7.0, spread: 360, direction: 270,
      gravity: 0, turbulence: 3.0, drag: 0.85, wind: 0, orbit: 0,
      particleSize: 2, particleShape: 'cross', sizeVariance: 1, hueVariation: 35,
      blendMode: 'prism', effectStrength: 1.9, startAlpha: 1, twinkle: 0.7, rotation: 0,
      lifetime: 14, fade: 1, shrink: 0,
      speedVariance: 0.7, velocityDecay: 0,
      deathCount: 4, deathSpeed: 5, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#1030ff',
      gradientStops: ['#ffffff', '#60e8ff', '#4070ff', '#1030ff'],
      bgColor: '#020310', trailAlpha: 0.32,
      trailEnabled: true, trailPersistence: 44, trailOpacity: 96, trailSoftness: 0,
    },
  },

  waterfall: {
    label: 'Waterfall',
    palette: 'ocean',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 18, emitterAngle: 5, pulseInterval: 2, emitterPX: 0.28, emitterPY: 0.05,
      count: 340, spawnRate: 220, speed: 5.2, spread: 8, direction: 90,
      gravity: 0.7, turbulence: 0.2, drag: 0.998, wind: 0.01, orbit: 0,
      particleSize: 2, particleShape: 'circle', sizeVariance: 1, hueVariation: 8,
      blendMode: 'glow', effectStrength: 1.0, startAlpha: 0.85, twinkle: 0.1, rotation: 0,
      lifetime: 120, fade: 0.7, shrink: 0,
      speedVariance: 0.25, velocityDecay: 0,
      deathCount: 3, deathSpeed: 2.0, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#e0ffff',
      gradientEnd: '#0840a0',
      gradientStops: ['#e0ffff', '#60c0ff', '#2080dd', '#0840a0'],
      bgColor: '#020810', trailAlpha: 0.08,
      trailEnabled: true, trailPersistence: 16, trailOpacity: 82, trailSoftness: 15,
    },
  },

  firework: {
    label: 'Firework',
    palette: 'neon',
    cfg: {
      emitterShape: 'point', emitterMode: 'burst', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.3,
      count: 300, spawnRate: 300, speed: 7.0, spread: 360, direction: 270,
      gravity: 0.2, turbulence: 0.15, drag: 0.955, wind: 0, orbit: 0,
      particleSize: 3, particleShape: 'star', sizeVariance: 2, hueVariation: 60,
      blendMode: 'glow', effectStrength: 1.9, startAlpha: 1, twinkle: 0.5, rotation: 5,
      lifetime: 95, fade: 1, shrink: 0.58,
      speedVariance: 0.4, velocityDecay: 0.22,
      deathCount: 6, deathSpeed: 3.0, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#5500cc',
      gradientStops: ['#ffffff', '#ffe060', '#ff4040', '#5500cc'],
      bgColor: '#040406', trailAlpha: 0.12,
      trailEnabled: true, trailPersistence: 20, trailOpacity: 92, trailSoftness: 4,
    },
  },

  leaves: {
    label: 'Leaves',
    palette: 'forest',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 50, emitterAngle: 12, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.0,
      count: 100, spawnRate: 18, speed: 1.0, spread: 38, direction: 108,
      gravity: 0.28, turbulence: 2.2, drag: 0.978, wind: 0.4, orbit: 0,
      particleSize: 5, particleShape: 'diamond', sizeVariance: 2, hueVariation: 20,
      blendMode: 'shadow', effectStrength: 1.1, shadowColor: '#1a1208',
      startAlpha: 0.95, twinkle: 0, rotation: 14,
      lifetime: 280, fade: 0.35, shrink: 0.01,
      speedVariance: 0.45, velocityDecay: 0.02,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#c8e060',
      gradientEnd: '#6a3818',
      gradientStops: ['#c8e060', '#88a840', '#a06830', '#6a3818'],
      bgColor: '#060a03', trailAlpha: 0.025,
      trailEnabled: true, trailPersistence: 5, trailOpacity: 55, trailSoftness: 12,
    },
  },

  comet: {
    label: 'Comet',
    palette: 'ice',
    cfg: {
      emitterShape: 'point', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.12, emitterPY: 0.14,
      count: 200, spawnRate: 170, speed: 3.0, spread: 16, direction: 138,
      gravity: 0, turbulence: 0.15, drag: 0.93, wind: 0, orbit: 0,
      particleSize: 3, particleShape: 'circle', sizeVariance: 1, hueVariation: 10,
      blendMode: 'glow', effectStrength: 1.7, startAlpha: 1, twinkle: 0.25, rotation: 0,
      lifetime: 58, fade: 1, shrink: 0.8,
      speedVariance: 0.2, velocityDecay: 0.3,
      deathCount: 3, deathSpeed: 1.8, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#1840aa',
      gradientStops: ['#ffffff', '#90e0ff', '#4080ff', '#1840aa'],
      bgColor: '#020408', trailAlpha: 0.18,
      trailEnabled: true, trailPersistence: 30, trailOpacity: 96, trailSoftness: 6,
    },
  },

  bubbles: {
    label: 'Bubbles',
    palette: 'aurora',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 40, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.95,
      count: 75, spawnRate: 20, speed: 0.45, spread: 22, direction: 270,
      gravity: -0.32, turbulence: 0.6, drag: 0.998, wind: 0, orbit: 0.06,
      particleSize: 9, particleShape: 'ring', sizeVariance: 5, hueVariation: 18,
      blendMode: 'glow', effectStrength: 0.9, startAlpha: 0.4, twinkle: 0.4, rotation: 0,
      lifetime: 260, fade: 0.5, shrink: -0.4,
      speedVariance: 0.28, velocityDecay: 0.05,
      deathCount: 3, deathSpeed: 1.5, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#e8ffff',
      gradientEnd: '#3090e0',
      gradientStops: ['#e8ffff', '#80eeff', '#50c0ff', '#3090e0'],
      bgColor: '#011018', trailAlpha: 0.03,
      trailEnabled: true, trailPersistence: 6, trailOpacity: 55, trailSoftness: 28,
    },
  },

  billiards: {
    label: 'Billiards',
    palette: 'retro',
    cfg: {
      emitterShape: 'point', emitterMode: 'burst', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 22, spawnRate: 22, speed: 7.0, spread: 360, direction: 270,
      gravity: 0, turbulence: 0, drag: 0.999, wind: 0, orbit: 0,
      particleSize: 10, particleShape: 'circle', sizeVariance: 2, hueVariation: 10,
      blendMode: 'shadow', effectStrength: 1.15, shadowColor: '#081208',
      startAlpha: 1, twinkle: 0, rotation: 0,
      lifetime: 350, fade: 0.04, shrink: 0,
      speedVariance: 0.2, velocityDecay: 0,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: false,
      gradientStart: '#ffb400',
      gradientEnd: '#ff5e5b',
      bgColor: '#0a1a0a', trailAlpha: 0.06,
      trailEnabled: true, trailPersistence: 12, trailOpacity: 82, trailSoftness: 0,
      bounce: true,
    },
  },

  laser: {
    label: 'Laser',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 5, emitterAngle: 90, pulseInterval: 2, emitterPX: 0.06, emitterPY: 0.5,
      count: 100, spawnRate: 140, speed: 10, spread: 3, direction: 0,
      gravity: 0, turbulence: 0.01, drag: 1, wind: 0, orbit: 0,
      particleSize: 2, particleShape: 'square', sizeVariance: 0, hueVariation: 0,
      blendMode: 'prism', effectStrength: 1.95, startAlpha: 1, twinkle: 0.1, rotation: 0,
      lifetime: 120, fade: 0.15, shrink: 0,
      speedVariance: 0, velocityDecay: 0,
      deathCount: 3, deathSpeed: 3.5, deathSize: 1,
      multiColor: false, useGradient: true,
      singleColor: '#ff4488',
      gradientStart: '#ff4488',
      gradientEnd: '#40e0ff',
      gradientStops: ['#ff4488', '#cc55ff', '#6080ff', '#40e0ff'],
      bgColor: '#030010', trailAlpha: 0.36,
      trailEnabled: true, trailPersistence: 50, trailOpacity: 100, trailSoftness: 0,
      bounce: true,
    },
  },

  stardust: {
    label: 'Stardust',
    palette: 'royal',
    cfg: {
      emitterShape: 'disk', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 44, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 250, spawnRate: 38, speed: 0.4, spread: 360, direction: 270,
      gravity: -0.02, turbulence: 0.8, drag: 1, wind: 0.02, orbit: 0.2,
      particleSize: 2, particleShape: 'sparkle', sizeVariance: 1, hueVariation: 28,
      blendMode: 'glow', effectStrength: 1.3, startAlpha: 0.9, twinkle: 1.4, rotation: 3,
      lifetime: 320, fade: 0.45, shrink: 0,
      speedVariance: 0.65, velocityDecay: 0,
      deathCount: 0, deathSpeed: 2, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#4028b0',
      gradientStops: ['#ffffff', '#c0a0ff', '#7050e0', '#4028b0'],
      bgColor: '#020206', trailAlpha: 0.015,
      trailEnabled: true, trailPersistence: 3, trailOpacity: 50, trailSoftness: 18,
    },
  },

  shockwave: {
    label: 'Shockwave',
    palette: 'storm',
    cfg: {
      emitterShape: 'point', emitterMode: 'burst', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 150, spawnRate: 150, speed: 9.0, spread: 360, direction: 270,
      gravity: 0, turbulence: 0.01, drag: 0.95, wind: 0, orbit: 0,
      particleSize: 6, particleShape: 'ring', sizeVariance: 3, hueVariation: 12,
      blendMode: 'glow', effectStrength: 1.95, startAlpha: 1, twinkle: 0.1, rotation: 0,
      lifetime: 48, fade: 1, shrink: 0.2,
      speedVariance: 0.15, velocityDecay: 0.48,
      deathCount: 4, deathSpeed: 3.5, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#0c3080',
      gradientStops: ['#ffffff', '#80d0ff', '#3070dd', '#0c3080'],
      bgColor: '#020610', trailAlpha: 0.2,
      trailEnabled: true, trailPersistence: 32, trailOpacity: 92, trailSoftness: 3,
    },
  },

  galaxy: {
    label: 'Galaxy',
    palette: 'royal',
    cfg: {
      emitterShape: 'disk', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 8, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 350, spawnRate: 90, speed: 1.9, spread: 360, direction: 270,
      gravity: 0, turbulence: 0.06, drag: 0.993, wind: 0, orbit: 2.0,
      particleSize: 2, particleShape: 'sparkle', sizeVariance: 1, hueVariation: 35,
      blendMode: 'prism', effectStrength: 1.55, startAlpha: 0.95, twinkle: 0.8, rotation: 6,
      lifetime: 200, fade: 0.68, shrink: 0.04,
      speedVariance: 0.32, velocityDecay: 0.04,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#280e60',
      gradientStops: ['#ffffff', '#a080ff', '#6030cc', '#280e60'],
      bgColor: '#020208', trailAlpha: 0.06,
      trailEnabled: true, trailPersistence: 12, trailOpacity: 78, trailSoftness: 10,
    },
  },

  phoenix: {
    label: 'Phoenix',
    palette: 'sunset',
    cfg: {
      emitterShape: 'arc', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 26, emitterAngle: 270, emitterArc: 170, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.56,
      count: 280, spawnRate: 130, speed: 4.2, spread: 50, direction: 264,
      gravity: -0.55, turbulence: 0.7, drag: 0.968, wind: 0, orbit: 0.5,
      particleSize: 3, particleShape: 'diamond', sizeVariance: 2, hueVariation: 20,
      blendMode: 'glow', effectStrength: 1.75, startAlpha: 1, twinkle: 0.3, rotation: 6,
      lifetime: 88, fade: 1, shrink: 0.35,
      speedVariance: 0.42, velocityDecay: 0.14,
      deathCount: 4, deathSpeed: 2.2, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#fff8b0',
      gradientEnd: '#600800',
      gradientStops: ['#fff8b0', '#ffc040', '#ff5000', '#600800'],
      bgColor: '#080308', trailAlpha: 0.1,
      trailEnabled: true, trailPersistence: 20, trailOpacity: 92, trailSoftness: 6,
    },
  },

  plasma: {
    label: 'Plasma',
    palette: 'neon',
    cfg: {
      emitterShape: 'circle', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 10, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 240, spawnRate: 150, speed: 3.0, spread: 360, direction: 270,
      gravity: 0, turbulence: 2.0, drag: 0.94, wind: 0, orbit: 1.1,
      particleSize: 3, particleShape: 'circle', sizeVariance: 1, hueVariation: 45,
      blendMode: 'prism', effectStrength: 1.95, startAlpha: 1, twinkle: 0.35, rotation: 0,
      lifetime: 35, fade: 1, shrink: 0.14,
      speedVariance: 0.52, velocityDecay: 0.06,
      deathCount: 3, deathSpeed: 3.5, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#4010cc',
      gradientStops: ['#ffffff', '#50f0ff', '#ff30cc', '#4010cc'],
      bgColor: '#030208', trailAlpha: 0.26,
      trailEnabled: true, trailPersistence: 38, trailOpacity: 96, trailSoftness: 4,
    },
  },

  fireflies: {
    label: 'Fireflies',
    palette: 'nature',
    cfg: {
      emitterShape: 'disk', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 44, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 85, spawnRate: 15, speed: 0.3, spread: 360, direction: 270,
      gravity: -0.06, turbulence: 0.5, drag: 0.996, wind: 0.08, orbit: 0.35,
      particleSize: 4, particleShape: 'circle', sizeVariance: 1, hueVariation: 18,
      blendMode: 'glow', effectStrength: 1.15, startAlpha: 0.9, twinkle: 0.95, rotation: 0,
      lifetime: 240, fade: 0.6, shrink: 0.06,
      speedVariance: 0.55, velocityDecay: 0.03,
      deathCount: 1, deathSpeed: 1.0, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffa0',
      gradientEnd: '#ff8800',
      gradientStops: ['#ffffa0', '#ffdd00', '#ffaa00', '#ff8800'],
      bgColor: '#090804', trailAlpha: 0.035,
      trailEnabled: true, trailPersistence: 8, trailOpacity: 62, trailSoftness: 20,
    },
  },
};
