/**
 * presets.js
 * Full effect presets - v0.1.9
 * Reworked to better use the expanded emitter, color, style, and motion toolset.
 */

const EFFECT_PRESETS = {
  fire: {
    label: 'Fire',
    palette: 'fire',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 30, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.9,
      count: 260, spawnRate: 150, speed: 3.7, spread: 22, direction: 268,
      gravity: -0.5, turbulence: 1.15, drag: 0.968, wind: 0.02, orbit: 0.18,
      particleSize: 4, particleShape: 'triangle', sizeVariance: 2, hueVariation: 12,
      blendMode: 'glow', effectStrength: 1.7, startAlpha: 1, twinkle: 0.18, rotation: 3,
      lifetime: 82, fade: 1, shrink: 0.38,
      speedVariance: 0.45, velocityDecay: 0.16,
      deathCount: 2, deathSpeed: 1.5, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffe08a',
      gradientEnd: '#5a0f00',
      gradientStops: ['#ffd86b', '#ff7a00', '#ff2b00', '#5a0f00'],
      bgColor: '#070508', trailAlpha: 0.11,
    },
  },

  snow: {
    label: 'Snow',
    palette: 'ice',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 48, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.0,
      count: 220, spawnRate: 56, speed: 0.9, spread: 26, direction: 92,
      gravity: 0.1, turbulence: 0.85, drag: 0.992, wind: 0.14, orbit: 0,
      particleSize: 3, particleShape: 'sparkle', sizeVariance: 2, hueVariation: 6,
      blendMode: 'glow', effectStrength: 0.45, startAlpha: 0.82, twinkle: 0.25, rotation: 2,
      lifetime: 290, fade: 0.55, shrink: 0.05,
      speedVariance: 0.42, velocityDecay: 0.02,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#274c7a',
      gradientStops: ['#dff7ff', '#89c5ff', '#274c7a'],
      bgColor: '#060b16', trailAlpha: 0.03,
    },
  },

  explosion: {
    label: 'Explosion',
    palette: 'lava',
    cfg: {
      emitterShape: 'point', emitterMode: 'burst', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 340, spawnRate: 340, speed: 7.8, spread: 360, direction: 270,
      gravity: 0.24, turbulence: 0.55, drag: 0.92, wind: 0, orbit: 0,
      particleSize: 4, particleShape: 'square', sizeVariance: 2, hueVariation: 22,
      blendMode: 'glow', effectStrength: 1.95, startAlpha: 1, twinkle: 0.12, rotation: 5,
      lifetime: 60, fade: 1, shrink: 0.58,
      speedVariance: 0.55, velocityDecay: 0.34,
      deathCount: 5, deathSpeed: 3, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#fff4b0',
      gradientEnd: '#3b0500',
      gradientStops: ['#fff4b0', '#ffb13b', '#ff3b00', '#3b0500'],
      bgColor: '#070406', trailAlpha: 0.18,
    },
  },

  sparkle: {
    label: 'Sparkle',
    palette: 'candy',
    cfg: {
      emitterShape: 'disk', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.48,
      count: 130, spawnRate: 55, speed: 1.6, spread: 360, direction: 270,
      gravity: -0.05, turbulence: 0.55, drag: 0.992, wind: 0, orbit: 0.35,
      particleSize: 5, particleShape: 'sparkle', sizeVariance: 3, hueVariation: 24,
      blendMode: 'prism', effectStrength: 1.15, startAlpha: 1, twinkle: 1.0, rotation: 10,
      lifetime: 95, fade: 1, shrink: 0.52,
      speedVariance: 0.28, velocityDecay: 0.06,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#fff4ff',
      gradientEnd: '#8a3cff',
      gradientStops: ['#fff4ff', '#ff7de0', '#8a3cff'],
      bgColor: '#06050d', trailAlpha: 0.05,
    },
  },

  magic: {
    label: 'Magic',
    palette: 'magic',
    cfg: {
      emitterShape: 'arc', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 18, emitterAngle: 270, emitterArc: 110, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.72,
      count: 170, spawnRate: 72, speed: 2.9, spread: 55, direction: 268,
      gravity: -0.4, turbulence: 1.2, drag: 0.973, wind: 0, orbit: 0.7,
      particleSize: 4, particleShape: 'star', sizeVariance: 2, hueVariation: 30,
      blendMode: 'prism', effectStrength: 1.25, startAlpha: 1, twinkle: 0.7, rotation: 7,
      lifetime: 118, fade: 1, shrink: 0.45,
      speedVariance: 0.32, velocityDecay: 0.1,
      deathCount: 2, deathSpeed: 1.8, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffd4ff',
      gradientEnd: '#4317a8',
      gradientStops: ['#ffd4ff', '#b46dff', '#4317a8'],
      bgColor: '#05030d', trailAlpha: 0.07,
    },
  },

  smoke: {
    label: 'Smoke',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 14, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.9,
      count: 90, spawnRate: 24, speed: 0.65, spread: 20, direction: 268,
      gravity: -0.38, turbulence: 0.75, drag: 0.982, wind: 0.08, orbit: 0,
      particleSize: 9, particleShape: 'circle', sizeVariance: 4, hueVariation: 0,
      blendMode: 'shadow', effectStrength: 1.15, shadowColor: '#1a1520',
      startAlpha: 0.28, twinkle: 0, rotation: 0,
      lifetime: 250, fade: 0.9, shrink: -0.45,
      speedVariance: 0.18, velocityDecay: 0.22,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: false, useGradient: false,
      singleColor: '#9c9aa2',
      gradientStart: '#9c9aa2',
      gradientEnd: '#4a4852',
      bgColor: '#09090c', trailAlpha: 0.025,
    },
  },

  confetti: {
    label: 'Confetti',
    palette: 'retro',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 48, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.0,
      count: 160, spawnRate: 70, speed: 4.6, spread: 46, direction: 92,
      gravity: 0.32, turbulence: 0.9, drag: 0.985, wind: 0.03, orbit: 0,
      particleSize: 5, particleShape: 'square', sizeVariance: 2, hueVariation: 28,
      blendMode: 'normal', effectStrength: 0.8, startAlpha: 1, twinkle: 0.15, rotation: 16,
      lifetime: 170, fade: 0.35, shrink: 0,
      speedVariance: 0.5, velocityDecay: 0.03,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: false,
      gradientStart: '#ffb400',
      gradientEnd: '#ff5e5b',
      bgColor: '#09090c', trailAlpha: 0.055,
    },
  },

  portal: {
    label: 'Portal',
    palette: 'aurora',
    cfg: {
      emitterShape: 'circle', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 20, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 260, spawnRate: 96, speed: 2.3, spread: 360, direction: 270,
      gravity: 0, turbulence: 0.14, drag: 0.986, wind: 0, orbit: 1.95,
      particleSize: 3, particleShape: 'ring', sizeVariance: 2, hueVariation: 18,
      blendMode: 'prism', effectStrength: 1.35, startAlpha: 0.95, twinkle: 0.55, rotation: 2,
      lifetime: 90, fade: 1, shrink: 0.65,
      speedVariance: 0.18, velocityDecay: 0.24,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#d7ffff',
      gradientEnd: '#120622',
      gradientStops: ['#d7ffff', '#6ad3ff', '#7a37ff', '#120622'],
      bgColor: '#02020f', trailAlpha: 0.14,
    },
  },

  rain: {
    label: 'Rain',
    palette: 'ocean',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 50, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.0,
      count: 340, spawnRate: 270, speed: 9.4, spread: 5, direction: 96,
      gravity: 0.08, turbulence: 0.04, drag: 1, wind: 0.08, orbit: 0,
      particleSize: 2, particleShape: 'square', sizeVariance: 0, hueVariation: 4,
      blendMode: 'shadow', effectStrength: 0.85, shadowColor: '#081a2f',
      startAlpha: 0.58, twinkle: 0, rotation: 0,
      lifetime: 58, fade: 0.65, shrink: 0,
      speedVariance: 0.18, velocityDecay: 0,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: false,
      gradientStart: '#b7e8ff',
      gradientEnd: '#0e57aa',
      bgColor: '#030812', trailAlpha: 0.2,
    },
  },

  healing: {
    label: 'Healing',
    palette: 'nature',
    cfg: {
      emitterShape: 'circle', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 16, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 120, spawnRate: 36, speed: 0.9, spread: 360, direction: 270,
      gravity: -0.28, turbulence: 0.55, drag: 0.986, wind: 0, orbit: 0.45,
      particleSize: 5, particleShape: 'heart', sizeVariance: 2, hueVariation: 12,
      blendMode: 'glow', effectStrength: 1.3, startAlpha: 0.96, twinkle: 0.35, rotation: 3,
      lifetime: 145, fade: 1, shrink: 0.36,
      speedVariance: 0.24, velocityDecay: 0.08,
      deathCount: 2, deathSpeed: 1, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#efffdc',
      gradientEnd: '#19a74c',
      gradientStops: ['#efffdc', '#8bff89', '#19a74c'],
      bgColor: '#020904', trailAlpha: 0.05,
    },
  },

  electric: {
    label: 'Electric',
    palette: 'neon',
    cfg: {
      emitterShape: 'point', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 190, spawnRate: 170, speed: 6.4, spread: 360, direction: 270,
      gravity: 0, turbulence: 2.6, drag: 0.87, wind: 0, orbit: 0,
      particleSize: 2, particleShape: 'cross', sizeVariance: 1, hueVariation: 30,
      blendMode: 'prism', effectStrength: 1.75, startAlpha: 1, twinkle: 0.65, rotation: 0,
      lifetime: 16, fade: 1, shrink: 0,
      speedVariance: 0.65, velocityDecay: 0,
      deathCount: 3, deathSpeed: 4, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#2346ff',
      gradientStops: ['#ffffff', '#5cf4ff', '#2346ff'],
      bgColor: '#02030f', trailAlpha: 0.3,
    },
  },

  waterfall: {
    label: 'Waterfall',
    palette: 'ocean',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 20, emitterAngle: 5, pulseInterval: 2, emitterPX: 0.3, emitterPY: 0.06,
      count: 300, spawnRate: 200, speed: 4.8, spread: 10, direction: 90,
      gravity: 0.6, turbulence: 0.25, drag: 0.997, wind: 0.01, orbit: 0,
      particleSize: 2, particleShape: 'circle', sizeVariance: 1, hueVariation: 10,
      blendMode: 'glow', effectStrength: 0.95, startAlpha: 0.88, twinkle: 0.12, rotation: 0,
      lifetime: 110, fade: 0.75, shrink: 0,
      speedVariance: 0.22, velocityDecay: 0,
      deathCount: 2, deathSpeed: 1.8, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#d7ffff',
      gradientEnd: '#0a4f9d',
      gradientStops: ['#d7ffff', '#47b7ff', '#0a4f9d'],
      bgColor: '#030812', trailAlpha: 0.07,
    },
  },

  firework: {
    label: 'Firework',
    palette: 'neon',
    cfg: {
      emitterShape: 'point', emitterMode: 'burst', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.32,
      count: 260, spawnRate: 260, speed: 6.3, spread: 360, direction: 270,
      gravity: 0.18, turbulence: 0.2, drag: 0.96, wind: 0, orbit: 0,
      particleSize: 3, particleShape: 'star', sizeVariance: 2, hueVariation: 55,
      blendMode: 'glow', effectStrength: 1.75, startAlpha: 1, twinkle: 0.45, rotation: 4,
      lifetime: 88, fade: 1, shrink: 0.62,
      speedVariance: 0.38, velocityDecay: 0.2,
      deathCount: 5, deathSpeed: 2.7, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#6318ff',
      gradientStops: ['#ffffff', '#ffd87a', '#ff4a36', '#6318ff'],
      bgColor: '#050508', trailAlpha: 0.1,
    },
  },

  leaves: {
    label: 'Leaves',
    palette: 'forest',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 48, emitterAngle: 10, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.0,
      count: 110, spawnRate: 20, speed: 1.1, spread: 34, direction: 104,
      gravity: 0.26, turbulence: 1.9, drag: 0.979, wind: 0.34, orbit: 0,
      particleSize: 5, particleShape: 'diamond', sizeVariance: 2, hueVariation: 18,
      blendMode: 'shadow', effectStrength: 1.05, shadowColor: '#20160c',
      startAlpha: 0.95, twinkle: 0, rotation: 11,
      lifetime: 260, fade: 0.38, shrink: 0.02,
      speedVariance: 0.4, velocityDecay: 0.03,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#bddf72',
      gradientEnd: '#7a4d22',
      gradientStops: ['#bddf72', '#7ea14a', '#7a4d22'],
      bgColor: '#060a04', trailAlpha: 0.03,
    },
  },

  comet: {
    label: 'Comet',
    palette: 'ice',
    cfg: {
      emitterShape: 'point', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.14, emitterPY: 0.16,
      count: 180, spawnRate: 150, speed: 2.6, spread: 18, direction: 135,
      gravity: 0, turbulence: 0.18, drag: 0.935, wind: 0, orbit: 0,
      particleSize: 3, particleShape: 'circle', sizeVariance: 1, hueVariation: 8,
      blendMode: 'glow', effectStrength: 1.55, startAlpha: 1, twinkle: 0.22, rotation: 0,
      lifetime: 62, fade: 1, shrink: 0.76,
      speedVariance: 0.18, velocityDecay: 0.28,
      deathCount: 2, deathSpeed: 1.5, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#2450ff',
      gradientStops: ['#ffffff', '#8ce9ff', '#2450ff'],
      bgColor: '#03040a', trailAlpha: 0.16,
    },
  },

  bubbles: {
    label: 'Bubbles',
    palette: 'aurora',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 38, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.94,
      count: 85, spawnRate: 24, speed: 0.55, spread: 20, direction: 270,
      gravity: -0.28, turbulence: 0.55, drag: 0.997, wind: 0, orbit: 0.05,
      particleSize: 8, particleShape: 'ring', sizeVariance: 4, hueVariation: 15,
      blendMode: 'glow', effectStrength: 0.85, startAlpha: 0.45, twinkle: 0.35, rotation: 0,
      lifetime: 240, fade: 0.55, shrink: -0.35,
      speedVariance: 0.24, velocityDecay: 0.06,
      deathCount: 2, deathSpeed: 1.3, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#dffeff',
      gradientEnd: '#45b1ff',
      gradientStops: ['#dffeff', '#86f7ff', '#45b1ff'],
      bgColor: '#021019', trailAlpha: 0.035,
    },
  },

  billiards: {
    label: 'Billiards',
    palette: 'retro',
    cfg: {
      emitterShape: 'point', emitterMode: 'burst', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 24, spawnRate: 24, speed: 6.4, spread: 360, direction: 270,
      gravity: 0, turbulence: 0, drag: 0.998, wind: 0, orbit: 0,
      particleSize: 9, particleShape: 'circle', sizeVariance: 2, hueVariation: 8,
      blendMode: 'shadow', effectStrength: 1.1, shadowColor: '#0a120a',
      startAlpha: 1, twinkle: 0, rotation: 0,
      lifetime: 320, fade: 0.05, shrink: 0,
      speedVariance: 0.18, velocityDecay: 0,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: false,
      gradientStart: '#ffb400',
      gradientEnd: '#ff5e5b',
      bgColor: '#0b190c', trailAlpha: 0.05, bounce: true,
    },
  },

  laser: {
    label: 'Laser',
    cfg: {
      emitterShape: 'line', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 6, emitterAngle: 90, pulseInterval: 2, emitterPX: 0.08, emitterPY: 0.5,
      count: 90, spawnRate: 120, speed: 9.5, spread: 4, direction: 0,
      gravity: 0, turbulence: 0.02, drag: 1, wind: 0, orbit: 0,
      particleSize: 2, particleShape: 'square', sizeVariance: 0, hueVariation: 0,
      blendMode: 'prism', effectStrength: 1.85, startAlpha: 1, twinkle: 0.12, rotation: 0,
      lifetime: 115, fade: 0.18, shrink: 0,
      speedVariance: 0, velocityDecay: 0,
      deathCount: 2, deathSpeed: 3, deathSize: 1,
      multiColor: false, useGradient: true,
      singleColor: '#ff5f9a',
      gradientStart: '#ff5f9a',
      gradientEnd: '#61f0ff',
      gradientStops: ['#ff5f9a', '#c56cff', '#61f0ff'],
      bgColor: '#040010', trailAlpha: 0.34, bounce: true,
    },
  },

  stardust: {
    label: 'Stardust',
    palette: 'royal',
    cfg: {
      emitterShape: 'disk', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 42, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 220, spawnRate: 36, speed: 0.45, spread: 360, direction: 270,
      gravity: -0.03, turbulence: 0.7, drag: 1, wind: 0.02, orbit: 0.18,
      particleSize: 2, particleShape: 'sparkle', sizeVariance: 1, hueVariation: 24,
      blendMode: 'glow', effectStrength: 1.2, startAlpha: 0.88, twinkle: 1.2, rotation: 2,
      lifetime: 300, fade: 0.5, shrink: 0,
      speedVariance: 0.6, velocityDecay: 0,
      deathCount: 0, deathSpeed: 2, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#5338d4',
      gradientStops: ['#ffffff', '#b287ff', '#5338d4'],
      bgColor: '#020207', trailAlpha: 0.018,
    },
  },

  shockwave: {
    label: 'Shockwave',
    palette: 'storm',
    cfg: {
      emitterShape: 'point', emitterMode: 'burst', speedMult: 1,
      emitterSize: 18, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 130, spawnRate: 130, speed: 8.5, spread: 360, direction: 270,
      gravity: 0, turbulence: 0.02, drag: 0.955, wind: 0, orbit: 0,
      particleSize: 6, particleShape: 'ring', sizeVariance: 3, hueVariation: 10,
      blendMode: 'glow', effectStrength: 1.85, startAlpha: 1, twinkle: 0.12, rotation: 0,
      lifetime: 52, fade: 1, shrink: 0.25,
      speedVariance: 0.18, velocityDecay: 0.45,
      deathCount: 3, deathSpeed: 3, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#113e88',
      gradientStops: ['#ffffff', '#74caff', '#113e88'],
      bgColor: '#020611', trailAlpha: 0.18,
    },
  },

  galaxy: {
    label: 'Galaxy',
    palette: 'royal',
    cfg: {
      emitterShape: 'disk', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 10, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 300, spawnRate: 82, speed: 1.7, spread: 360, direction: 270,
      gravity: 0, turbulence: 0.08, drag: 0.992, wind: 0, orbit: 1.75,
      particleSize: 2, particleShape: 'sparkle', sizeVariance: 1, hueVariation: 30,
      blendMode: 'prism', effectStrength: 1.45, startAlpha: 0.95, twinkle: 0.7, rotation: 5,
      lifetime: 180, fade: 0.72, shrink: 0.06,
      speedVariance: 0.28, velocityDecay: 0.05,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#37156f',
      gradientStops: ['#ffffff', '#8c76ff', '#37156f'],
      bgColor: '#02020a', trailAlpha: 0.05,
    },
  },

  phoenix: {
    label: 'Phoenix',
    palette: 'sunset',
    cfg: {
      emitterShape: 'arc', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 24, emitterAngle: 270, emitterArc: 160, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.58,
      count: 240, spawnRate: 110, speed: 3.9, spread: 55, direction: 266,
      gravity: -0.48, turbulence: 0.65, drag: 0.972, wind: 0, orbit: 0.45,
      particleSize: 3, particleShape: 'diamond', sizeVariance: 2, hueVariation: 18,
      blendMode: 'glow', effectStrength: 1.65, startAlpha: 1, twinkle: 0.25, rotation: 5,
      lifetime: 92, fade: 1, shrink: 0.32,
      speedVariance: 0.38, velocityDecay: 0.12,
      deathCount: 3, deathSpeed: 2, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#fff0b0',
      gradientEnd: '#6f0e00',
      gradientStops: ['#fff0b0', '#ffb54a', '#ff4b00', '#6f0e00'],
      bgColor: '#09040a', trailAlpha: 0.09,
    },
  },

  plasma: {
    label: 'Plasma',
    palette: 'neon',
    cfg: {
      emitterShape: 'circle', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 12, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 210, spawnRate: 130, speed: 2.8, spread: 360, direction: 270,
      gravity: 0, turbulence: 1.7, drag: 0.945, wind: 0, orbit: 0.95,
      particleSize: 3, particleShape: 'circle', sizeVariance: 1, hueVariation: 40,
      blendMode: 'prism', effectStrength: 1.85, startAlpha: 1, twinkle: 0.32, rotation: 0,
      lifetime: 38, fade: 1, shrink: 0.16,
      speedVariance: 0.48, velocityDecay: 0.08,
      deathCount: 2, deathSpeed: 3.2, deathSize: 1,
      multiColor: true, useGradient: true,
      gradientStart: '#ffffff',
      gradientEnd: '#5d19ff',
      gradientStops: ['#ffffff', '#67f3ff', '#ff39cc', '#5d19ff'],
      bgColor: '#04020a', trailAlpha: 0.24,
    },
  },

  fireflies: {
    label: 'Fireflies',
    palette: 'nature',
    cfg: {
      emitterShape: 'disk', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 44, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 64, spawnRate: 10, speed: 0.28, spread: 360, direction: 270,
      gravity: -0.01, turbulence: 1.25, drag: 0.997, wind: 0.02, orbit: 0.25,
      particleSize: 3, particleShape: 'circle', sizeVariance: 1, hueVariation: 10,
      blendMode: 'glow', effectStrength: 1.9, startAlpha: 0.82, twinkle: 1.55, rotation: 0,
      lifetime: 300, fade: 0.68, shrink: 0,
      speedVariance: 0.8, velocityDecay: 0,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#cfff86',
      gradientEnd: '#284c12',
      gradientStops: ['#cfff86', '#7bf14c', '#284c12'],
      bgColor: '#040804', trailAlpha: 0.025,
    },
  },

  vortex: {
    label: 'Vortex',
    palette: 'aurora',
    cfg: {
      emitterShape: 'circle', emitterMode: 'continuous', speedMult: 1,
      emitterSize: 28, emitterAngle: 0, pulseInterval: 2, emitterPX: 0.5, emitterPY: 0.5,
      count: 320, spawnRate: 120, speed: 1.7, spread: 360, direction: 270,
      gravity: 0, turbulence: 0.05, drag: 0.987, wind: 0, orbit: -2,
      particleSize: 2, particleShape: 'triangle', sizeVariance: 1, hueVariation: 20,
      blendMode: 'prism', effectStrength: 1.35, startAlpha: 0.9, twinkle: 0.4, rotation: 2,
      lifetime: 160, fade: 0.82, shrink: 0.22,
      speedVariance: 0.16, velocityDecay: 0.09,
      deathCount: 0, deathSpeed: 2, deathSize: 2,
      multiColor: true, useGradient: true,
      gradientStart: '#d9ffff',
      gradientEnd: '#14082e',
      gradientStops: ['#d9ffff', '#6fd8ff', '#824bff', '#14082e'],
      bgColor: '#020208', trailAlpha: 0.08,
    },
  },
};
